name: Deploy Serverless Feedback Application

on:
  push:
    branches:
      - main

jobs:
  security-scans:
    name: 1. Security Scans
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install security tools
        run: pip install cfn-lint bandit pip-audit

      - name: Run cfn-lint
        run: cfn-lint template.yaml

      - name: Run bandit
        run: bandit -r src/

      

  deploy:
    name: 2. Build and Deploy
    runs-on: ubuntu-latest
    needs: security-scans # This job only runs if security-scans job passes
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: SAM Build
        run: sam build --use-container
      
      - name: Clear Sam config
        run : rm -f samconfig.toml

      - name: SAM Deploy
        run: >
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
          --stack-name serverless-feedback-app
          --s3-bucket feedback-form-artifacts-bucket
          --capabilities CAPABILITY_IAM
          --parameter-overrides SnsEmailParameter=${{ secrets.SNS_EMAIL_ADDRESS }}

      - name: Sync Frontend to S3
        run: |
          aws s3 sync ./frontend s3://feedback-frontend-bucket-dev --delete